# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # for JavaScript dependencies
    directory: "/" # location of your package.json file
    schedule:
      interval: "weekly" # check for updates weekly
    commit-message:
      prefix: "fix" # prefix for the commit messages
    open-pull-requests-limit: 5 # maximum number of open pull requests at a time
